# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

 # If you come from bash you might have to change your $PATH.
 export PATH=$HOME/bin:/usr/local/bin:$PATH

 # Path to your oh-my-zsh installation.
 export ZSH=$HOME/.oh-my-zsh

 # Custom scripts
 export PATH=$HOME/scripts:$PATH

 # Set name of the theme to load --- if set to "random", it will
 # load a random theme each time oh-my-zsh is loaded, in which case,
 # to know which specific one was loaded, run: echo $RANDOM_THEME
 # See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
 ZSH_THEME="powerlevel10k/powerlevel10k"

function prompt_gdir() {
  dir=$(pwd)
  if [[ "$dir" =~ ^(\/google\/src\/cloud)(\/([^/]+\/)*)(.*)$ ]]; then
    CURRENT_DIRECTORY="//.../${match[3]}${match[4]}"
    CUSTOM_GLYPH=$'\uf1a0 '
  else
    CURRENT_DIRECTORY="$dir"
    CUSTOM_GLYPH=$'\uf07c '
  fi
  HOME_DIRECTORY_SYMBOL="~"
  TARGET_HOME_DIRECTORY="$HOME"
  FORMATTED_DIRECTORY="${CURRENT_DIRECTORY/$TARGET_HOME_DIRECTORY/$HOME_DIRECTORY_SYMBOL}"
  p10k segment -b blue -f '$POWERLEVEL9K_DIR_FOREGROUND' -t "$CUSTOM_GLYPH $FORMATTED_DIRECTORY"
}

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# User configuration

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Colours
export CLICOLOR=1
export TERM=xterm-256color

alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"
alias vimconfig="vim ~/.vimrc"
alias ssh-tmux="~/bin/ssh-tmux"
alias chromium="$HOME/scripts/./chromium.sh"
alias pbcopy="$HOME/pbcopy.sh"
alias gitrc="git rebase --continue && git rebase-update --no-fetch"

alias ls="ls -G"
alias finder="open ."

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_TMUX_OPTS="-p"
export FZF_CTRL_R_OPTS="--reverse --preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"

__git_files () {
  _wanted files expl 'local files' _files
}

export NVM_DIR="/Users/meredith/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

source /etc/bash_completion.d/hgd
export PATH="${PATH}:${HOME}/bin"

fixup_ssh_auth_sock() {
  if [[ -n ${SSH_AUTH_SOCK} && ! -e ${SSH_AUTH_SOCK} ]]
  then
    local new_sock=$(echo /tmp/ssh-*/agent.*(=UNom[1]))
     if [[ -n ${new_sock} ]]
     then
       export SSH_AUTH_SOCK=${new_sock}
     fi
  fi
}
if [[ -n ${SSH_AUTH_SOCK} ]]
then
  autoload -U add-zsh-hook
  add-zsh-hook preexec fixup_ssh_auth_sock
fi
